# Generated by Django 2.2.17 on 2020-11-19 13:18

from django.db import migrations, models
import django.db.models.deletion

from wagtail import VERSION as WAGTAIL_VERSION

if WAGTAIL_VERSION >= (3, 0):
    import wagtail.blocks as wagtail_blocks
    import wagtail.fields as wagtail_fields
else:
    import wagtail.core.blocks as wagtail_blocks
    import wagtail.core.fields as wagtail_fields
    
import wagtail_webstories.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('publisher', models.CharField(max_length=2047)),
                ('publisher_logo_src', models.URLField(max_length=2047, verbose_name='Publisher logo URL')),
                ('poster_portrait_src', models.URLField(max_length=2047, verbose_name='Poster portrait image URL')),
                ('poster_square_src', models.URLField(blank=True, max_length=2047, verbose_name='Poster square image URL')),
                ('poster_landscape_src', models.URLField(blank=True, max_length=2047, verbose_name='Poster landscape image URL')),
                ('custom_css', models.TextField(blank=True)),
                ('pages', wagtail_fields.StreamField([('page', wagtail_blocks.StructBlock([('id', wagtail_blocks.CharBlock()), ('html', wagtail_webstories.blocks.AMPCleanHTMLBlock())]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
