# Generated by Django 2.2.17 on 2020-11-19 16:28

import django.db.models.deletion
import wagtail.blocks as wagtail_blocks
import wagtail.fields as wagtail_fields
from django.db import migrations, models

import wagtail_webstories.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.Page",
                    ),
                ),
                (
                    "body",
                    wagtail_fields.StreamField(
                        [
                            ("heading", wagtail_blocks.CharBlock()),
                            (
                                "story_embed",
                                wagtail_webstories.blocks.StoryEmbedBlock(),
                            ),
                            (
                                "story_link",
                                wagtail_webstories.blocks.StoryChooserBlock(),
                            ),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
