# Generated by Django 2.2.17 on 2020-11-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('tests', '0002_blogpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storypage',
            old_name='poster_landscape_src',
            new_name='poster_landscape_src_original',
        ),
        migrations.RenameField(
            model_name='storypage',
            old_name='poster_portrait_src',
            new_name='poster_portrait_src_original',
        ),
        migrations.RenameField(
            model_name='storypage',
            old_name='poster_square_src',
            new_name='poster_square_src_original',
        ),
        migrations.RenameField(
            model_name='storypage',
            old_name='publisher_logo_src',
            new_name='publisher_logo_src_original',
        ),
        migrations.AddField(
            model_name='storypage',
            name='poster_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='storypage',
            name='poster_landscape_src_original',
            field=models.URLField(blank=True, editable=False, max_length=2047, verbose_name='Poster landscape image URL'),
        ),
        migrations.AlterField(
            model_name='storypage',
            name='poster_portrait_src_original',
            field=models.URLField(blank=True, editable=False, max_length=2047, verbose_name='Poster portrait image URL'),
        ),
        migrations.AlterField(
            model_name='storypage',
            name='poster_square_src_original',
            field=models.URLField(blank=True, editable=False, max_length=2047, verbose_name='Poster square image URL'),
        ),
        migrations.AddField(
            model_name='storypage',
            name='publisher_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='storypage',
            name='publisher_logo_src_original',
            field=models.URLField(blank=True, editable=False, max_length=2047, verbose_name='Publisher logo URL'),
        ),
    ]
